In [2]:
import polars as pl
import pandas as pd
import numpy as np
from pathlib import Path

In [10]:

THIS_FOLDER = Path('.')

RAW_FOLDER = THIS_FOLDER / 'raw' / 'walmes_tcc_brasil_neto'
ABT_FOLDER = THIS_FOLDER / 'abt'

In [16]:

df_alvaras = pd.read_csv(RAW_FOLDER / 'alvaras.csv', sep=';', encoding='latin-1', low_memory=False)
df_alvaras.head()

,NOME_EMPRESARIAL,INICIO_ATIVIDADE,NUMERO_DO_ALVARA,NOME_DA_EMPRESA,DATA_EMISSAO,DATA_EXPIRACAO,ATIVIDADE_PRINCIPAL,ATIVIDADE_SECUNDARIA1,ATIVIDADE_SECUNDARIA2,ENDERECO,NUMERO,UNIDADE,ANDAR,COMPLEMENTO,BAIRRO,CEP
0,"(MPDS) MEIO AMBIENTE, PESSOAS E O DESENVOLVIME...",04/02/2014,1169609,"(MPDS) MEIO AMBIENTE, PESSOAS E O DESENVOLVIMENTO",26/02/2014,***,ATIVIDADES DE ASSOCIAÇÕES DE DEFESA DE DIREITO...,***,***,R. JOSÉ WALDEMAR BARON,000239,***,***,***,CACHOEIRA,82710190
1,(RBDS) NO RASTRO DA BIODIVERSIDADE E DO DESENV...,14/12/2012,1119982,(RBDS) NO RASTRO DA BIODIVERSIDADE E DO DESENV...,18/02/2013,***,ATIVIDADES DE ASSOCIAÇÕES DE DEFESA DE DIREITO...,***,***,R. DIONIZIO MARKOVICZ,000155,***,***,***,CIDADE INDUSTRIAL,81240160
2,+55 ADMINISTRADORA DE BENS LTDA.,24/03/2016,1263563,+55 ADMINISTRADORA,30/03/2016,31/12/2017,GESTÃO E ADMINISTRAÇÃO DA PROPRIEDADE IMOBILIÁRIA,LOTEAMENTO DE IMÓVEIS PRÓPRIOS,ALUGUEL DE IMÓVEIS PRÓPRIOS,R. EVALDO WENDLER,000090,CS68,***,***,SÃO LOURENÇO,82200180
3,+55 ADMINISTRADORA DE BENS LTDA.,24/03/2016,1351366,+55 ADMINISTRADORA,20/12/2017,***,GESTÃO E ADMINISTRAÇÃO DA PROPRIEDADE IMOBILIÁRIA,LOTEAMENTO DE IMÓVEIS PRÓPRIOS,ALUGUEL DE IMÓVEIS PRÓPRIOS,R. EVALDO WENDLER,000090,CS68,***,***,SÃO LOURENÇO,82200180
4,- ODIR LOPES ACABAMENTOS GRAFICOS - ME,21/10/2003,1033277,***,05/09/2011,27/07/2013,"TRANSPORTE RODOVIÁRIO DE CARGA, EXCETO PRODUTO...",***,***,RUA WALDIR PONTES,112,***,***,***,CAMPO COMPRIDO,***

In [18]:

df_alvaras_final = pd.read_csv(RAW_FOLDER / 'alvaras_final.csv', sep=';', encoding='latin-1', low_memory=False)
df_alvaras_final.head()

,NOME_EMPRESARIAL,INICIO_ATIVIDADE,NUMERO_DO_ALVARA,NOME_DA_EMPRESA,DATA_EMISSAO,DATA_EXPIRACAO,ATIVIDADE_PRINCIPAL,ATIVIDADE_SECUNDARIA1,ATIVIDADE_SECUNDARIA2,ENDERECO,NUMERO,UNIDADE,ANDAR,COMPLEMENTO,BAIRRO,CEP,cat,lat1,lon1
0,100 PIZZA LTDA,1998-07-01,555857,100 PIZZA LTDA,2002-01-02,NaN,PIZZARIA,COMERCIO VAREJISTA DE BEBIDAS,NaN,ALAMEDA NOSSA SENHORA DO SAGRADO CORACAO,713.0,NaN,NaN,TR,PINHEIRINHO,81710000.0,alimentacao,"-25,5300135","-49,2945821"
1,280 PARK ESTACIONAMENTO LTDA - ME,2015-04-17,1294928,280 PARK ESTACIONAMENTO LTDA - ME,2016-12-02,NaN,ESTACIONAMENTO DE VEICULOS,NaN,NaN,RUA PROFESSORA ROSA SAPORSKI,280.0,NaN,NaN,NaN,MERCES,80810120.0,estacionamento,"-25,4242112","-49,2908575"
2,3A PROJETOS EDUCACIONAIS LTDA - ME,2016-03-22,1263386,3A PROJETOS EDUCACIONAIS,2016-03-29,NaN,ATIVIDADES DE APOIO A EDUCACAO,NaN,NaN,RUA PROFESSOR DARIO VELOSO,467.0,102,01,NaN,VILA IZABEL,80320050.0,educacao,NaN,NaN
3,3BS MULTISERVICES LTDA - ME,2013-12-10,1165216,WORLD EDIOMAS,2014-01-23,NaN,ENSINO DE IDIOMAS,PREPARACAO DE DOCUMENTOS E SERVICOS ESPECIALIZ...,OUTRAS ATIVIDADES DE SERVICOS PRESTADOS PRINCI...,RUA VERONICA MICKOSZ BODZINSKI,175.0,NaN,NaN,NaN,TABOAO,82130295.0,educacao,NaN,NaN
4,3MD CURSOS E CLINICA ODONTOLOGICA LTDA,2008-12-05,1363551,STUDIA,2018-04-03,NaN,EDUCACAO SUPERIOR - GRADUACAO E POS-GRADUACAO,SERVICOS DE DIAGNOSTICO POR IMAGEM COM USO DE ...,ATIVIDADE ODONTOLOGICA,AVENIDA IGUACU,1745.0,NaN,NaN,NaN,AGUA VERDE,80240030.0,educacao,"-25,445625","-49,2785147"

In [20]:

df_ends = pd.read_csv(RAW_FOLDER / 'ends.csv', sep=';', encoding='latin-1', low_memory=False)
df_ends.head()

                                   ENDERECO         lat1         lon1
0  ALAMEDA NOSSA SENHORA DO SAGRADO CORACAO  -25,5300135  -49,2945821
1              RUA PROFESSORA ROSA SAPORSKI  -25,4242112  -49,2908575
2                            AVENIDA IGUACU   -25,445625  -49,2785147
3                     ALAMEDA DOUTOR MURICY  -25,4342195  -49,2713835
4                RUA DEPUTADO ARDINAL RIBAS  -25,5042121  -49,3019085

In [21]:

df_imoveis_web_features = pd.read_csv(RAW_FOLDER / 'ImoveisWeb-Feature.csv', sep=';', encoding='latin-1', low_memory=False)
df_imoveis_web_features.head()

   realty                       word    name
0       1               Aceita FGTS   Outros
1       1                Andares (7)  Outros
2       1                   Ocupado   Outros
3       1  Posição do Apto (Lateral)  Outros
4       1  Posição do Sol (Nascente)  Outros

In [22]:

df_imoveis_web_realty = pd.read_csv(RAW_FOLDER / 'ImoveisWeb-Realty.csv', sep=';', encoding='latin-1', low_memory=False)
df_imoveis_web_realty.head()

,id,url,type,title,description,address,lat,lon,pictures,iptu,...,totalArea,bedroom,suite,bathroom,garage,price,years,publishment,advertiser,CRECI
0,1,propriedades/excelente-oportunidade-no-bouleva...,Apartamento,excelente oportunidade no boulevard iguaçu - 2...,\nDescrição O Boulevard Iguaçu é um empreendim...,"Avenida Iguaçu, Água Verde, Curitiba","-25,4474","-49,2831",31,"720,00",...,"95,00",2.0,1.0,2.0,2.0,"649900,00",5.0,2.0,PRIME SOHO IMÓVEIS P33,NaN
1,2,propriedades/residencial-mont-bello.-excelente...,Casa,Residencial Mont Bello. Excelente unidades int...,\nResidencial Mont Bello. Um residencial com a...,"Rua Barão de Monte Alegre, Jardim das Américas...","-25,4609","-49,2246",8,NaN,...,"107,00",3.0,1.0,1.0,1.0,"460000,00",NaN,31.0,HABITARTE IMÓVEIS,3929J
2,3,propriedades/apartamento-residencial-a-venda-n...,Apartamento,"Apartamento residencial à venda, Novo Mundo, C...","\nEmpreendimento recém lançado, apartamentos a...","Rua Antônio Gasparin 5677, Novo Mundo, Curitiba","-25,4955","-49,2953",31,NaN,...,"99,00",2.0,1.0,2.0,1.0,"395000,00",NaN,108.0,M.A Corretora de Imoveis,F22018
3,4,propriedades/excelente-terreno-novo-mundo-zr4-...,Terreno,Excelente terreno novo mundo zr4,\nTerreno plano com 520mts sendo 13x40 zr4 com...,"Avenida Presidente Getúlio Vargas 486, Novo Mu...","-25,4419","-49,2649",3,NaN,...,"500,00",NaN,NaN,NaN,NaN,"490000,00",NaN,13.0,REZENDE IMÓVEIS,22256PR
4,5,propriedades/terreno-a-venda-em-bigorrilho-293...,Terreno,Terreno à venda - em Bigorrilho,"\nÓtimo terreno, no Bigorrilho, um dos melhore...","Rua Euclides da Cunha 1639, Bigorrilho, Curitiba","-25,4311","-49,2998",10,NaN,...,"769,00",NaN,NaN,NaN,NaN,"1200000,00",NaN,347.0,Partner Imóveis,NaN

In [51]:
! pip install unidecode

Collecting unidecode
  Downloading Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Downloading Unidecode-1.4.0-py3-none-any.whl (235 kB)
Installing collected packages: unidecode
Successfully installed unidecode-1.4.0

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [72]:
from unidecode import unidecode


df_features = (

    pl.DataFrame(df_imoveis_web_features)

    # Handle the text
    .with_columns(

            pl.col("realty").cast(pl.Int64).alias("id_realty"),

            (
                "fg_has_"
                + pl.col('name')
                    .str.to_lowercase()
                    .str.replace_all(r"\s*\([^()]*\)", "")
                    .str.strip_chars()
                    .map_elements(unidecode)
                    .str.replace_all(r'\s+', '_') 
                + "_" 
                + pl.col('word')
                    .str.to_lowercase()
                    .str.replace_all(r"\s*\([^()]*\)", "")
                    .str.strip_chars()
                    .map_elements(unidecode)
                    .str.replace_all(r'\s+', '_')
            ).alias('combined'),

            pl.lit(1).alias('value')
    )


    # Pivot house features to columns
    .pivot(
        on='combined', 
        index='id_realty', 
        values='value', 
        aggregate_function='max',
    ).fill_null(0)

)

df_features.head()

shape: (5, 210)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_realty ┆ fg_has_ou ┆ fg_has_ou ┆ fg_has_ou ┆ … ┆ fg_has_ar ┆ fg_has_ar ┆ fg_has_ar ┆ fg_has_a │
│ ---       ┆ tros_acei ┆ tros_anda ┆ tros_ocup ┆   ┆ eas_comun ┆ eas_comun ┆ eas_comun ┆ reas_com │
│ i64       ┆ ta_fgts   ┆ res       ┆ ado       ┆   ┆ s_quintal ┆ s_ar_cond ┆ s_copa    ┆ uns_meza │
│           ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ici…      ┆ ---       ┆ nino     │
│           ┆ i32       ┆ i32       ┆ i32       ┆   ┆ i32       ┆ ---       ┆ i32       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ i32       ┆           ┆ i32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 1         ┆ 1         ┆ 1         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 2         ┆ 1         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 20        ┆ 0         ┆ 1         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 39        ┆ 1         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 47        ┆ 1         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [97]:

df_realty = (
    
    # Original DF
    pl.DataFrame(df_imoveis_web_realty)

    # Handle dtypes
    .with_columns(
        pl.col('id').cast(pl.Int64).alias('id_realty'), 
        pl.col('price').str.replace(",", ".").cast(pl.Float64).fill_null(0).alias('vl_price'),
        pl.col('pictures').cast(pl.Int64).fill_null(0).alias('n_pictures'),
        pl.col('iptu').str.replace(",", ".").cast(pl.Float64).fill_null(0).alias('vl_iptu'),
        pl.col('condominium').str.replace(",", ".").cast(pl.Float64).fill_null(0).alias('vl_condominium'),
        pl.col('totalArea').str.replace(",", ".").cast(pl.Float64).fill_null(0).alias('vl_total_area'),
        pl.col('usefulArea').str.replace(",", ".").cast(pl.Float64).fill_null(0).alias('vl_useable_area'),
        pl.col('bedroom').cast(pl.Int64).fill_null(0).alias('n_bedrooms'),
        pl.col('bathroom').cast(pl.Int64).fill_null(0).alias('n_bathrooms'),
        pl.col('garage').cast(pl.Int64).fill_null(0).alias('n_garages'),
        pl.col('years').cast(pl.Int64).fill_null(0).alias('n_years'),
        pl.col('type').cast(pl.String).alias('nm_type'),
        pl.col('title').cast(pl.Utf8).alias('nm_title'),
    )

    # Join with features
    .join(
        df_features, 
        on='id_realty', 
        how='left'
    ).with_columns(
        [
            pl.col(col).fill_null(0) 
            for col in df_features.columns 
            if col != 'id_realty'
        ]
    )

    # Add string features
    .with_columns(
        pl.col('title').cast(pl.Utf8).alias('nm_title'),
        pl.col('description').cast(pl.Utf8).alias('nm_description'),
        pl.col('address').cast(pl.Utf8).alias('nm_address'),
    )

    # Keep only columns of interest (startedd with id_, vl_, n_, nm_, fg_)
    .drop([_ for _ in df_imoveis_web_realty.columns], strict=False)

)

df_realty

shape: (71_316, 224)
┌───────────┬──────────┬────────────┬─────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ id_realty ┆ vl_price ┆ n_pictures ┆ vl_iptu ┆ … ┆ fg_has_are ┆ fg_has_ar ┆ nm_descri ┆ nm_addres │
│ ---       ┆ ---      ┆ ---        ┆ ---     ┆   ┆ as_comuns_ ┆ eas_comun ┆ ption     ┆ s         │
│ i64       ┆ f64      ┆ i64        ┆ f64     ┆   ┆ copa       ┆ s_mezanin ┆ ---       ┆ ---       │
│           ┆          ┆            ┆         ┆   ┆ ---        ┆ o         ┆ str       ┆ str       │
│           ┆          ┆            ┆         ┆   ┆ i32        ┆ ---       ┆           ┆           │
│           ┆          ┆            ┆         ┆   ┆            ┆ i32       ┆           ┆           │
╞═══════════╪══════════╪════════════╪═════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 1         ┆ 649900.0 ┆ 31         ┆ 720.0   ┆ … ┆ 0          ┆ 0         ┆           ┆ Avenida   │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ Descrição ┆ Iguaçu,   │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ O         ┆ Água      │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ Boulevard ┆ Verde,    │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ Iguaçu …  ┆ Cu…       │
│ 2         ┆ 460000.0 ┆ 8          ┆ 0.0     ┆ … ┆ 0          ┆ 0         ┆           ┆ Rua Barão │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ Residenci ┆ de Monte  │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ al Mont   ┆ Alegre,   │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ Bello. Um ┆ Jar…      │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ re…       ┆           │
│ 3         ┆ 395000.0 ┆ 31         ┆ 0.0     ┆ … ┆ 0          ┆ 0         ┆           ┆ Rua       │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ Empreendi ┆ Antônio   │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ mento     ┆ Gasparin  │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ recém     ┆ 5677, No… │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ lançado,… ┆           │
│ 4         ┆ 490000.0 ┆ 3          ┆ 0.0     ┆ … ┆ 0          ┆ 0         ┆           ┆ Avenida   │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ Terreno   ┆ President │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ plano com ┆ e Getúlio │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ 520mts    ┆ Var…      │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ send…     ┆           │
│ 5         ┆ 1.2e6    ┆ 10         ┆ 0.0     ┆ … ┆ 0          ┆ 0         ┆           ┆ Rua       │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ Ótimo     ┆ Euclides  │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ terreno,  ┆ da Cunha  │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ no Bigorr ┆ 1639, Bi… │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ ilho,…    ┆           │
│ …         ┆ …        ┆ …          ┆ …       ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 71312     ┆ 150000.0 ┆ 27         ┆ 0.0     ┆ … ┆ 0          ┆ 0         ┆           ┆ DALILA    │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ Excelente ┆ LOPES     │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ apartamen ┆ COSTA     │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ to em     ┆ 108,      │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ cond…     ┆ Uberab…   │
│ 71313     ┆ 275000.0 ┆ 17         ┆ 0.0     ┆ … ┆ 0          ┆ 0         ┆           ┆ Rua       │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ Sobrado   ┆ Irineu    │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ de frente ┆ Prevedell │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ para rua  ┆ o Tedesco │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ no…       ┆ …         │
│ 71314     ┆ 580000.0 ┆ 40         ┆ 0.0     ┆ … ┆ 0          ┆ 0         ┆           ┆ Rua       │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ Excelente ┆ Auguste   │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ sobrado   ┆ Conte     │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ reformado ┆ 170,      │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ , …       ┆ Santa F…  │
│ 71315     ┆ 222000.0 ┆ 15         ┆ 0.0     ┆ … ┆ 0          ┆ 0         ┆           ┆ R.        │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ Ligue ou  ┆ Alberto   │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ envie um  ┆ Kosop,    │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ whats E   ┆ 280,      │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ age…      ┆ Pinheir…  │
│ 71316     ┆ 429000.0 ┆ 15         ┆ 0.0     ┆ … ┆ 0          ┆ 0         ┆           ┆ Rua São   │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ Excelente ┆ Paulo, ,  │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ oportunid ┆ Água      │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ ade em    ┆ Verde, C… │
│           ┆          ┆            ┆         ┆   ┆            ┆           ┆ apa…      ┆           │
└───────────┴──────────┴────────────┴─────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [98]:

df_realty.to_pandas().to_parquet(
    ABT_FOLDER / '1_abt_realty.parquet', 
    index=False,
)